### ISSUE TITLE
请问支持ONE API吗？我设了ONE API后不能用

### ISSUE THREAD

**Issue by cq134cq** [AIDotNet/fast-wiki#14]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
请问支持ONE API吗？我设了ONE API后不能用

**Comment by 239573049** [comment]
支持的，不能用的话请提供错误图片或者日志。
可能存在的原因
- 您没有给创建token的额度
- 您没有创建渠道

**Comment by cq134cq** [comment]
> * 有创建渠道

environment:
      - OPENAI_CHAT_ENDPOINT=http://10.0.100.176:3002
      - OPENAI_CHAT_EMBEDDING_ENDPOINT=http://10.0.100.176:3002
      - OPENAI_CHAT_TOKEN={sk-Ig5Y2Lq1nluNvYZE81B4B1F11cA84d1eAb112eE4C826De94}
      - OPENAI_CHAT_MODEL=gpt-3.5-turbo
      - OPENAI_EMBEDDING_MODEL=text-embedding-3-small
      - ASPNETCORE_ENVIRONMENT=Development

**Comment by 239573049** [comment]
加一下群，在群里聊
![image](https://github.com/239573049/fast-wiki/assets/61819790/fe4bbf82-8a05-42af-a9bf-258ea7337378)
