### ISSUE TITLE
[feature] 框架设计

### ISSUE THREAD

**Issue by 239573049** [AIDotNet/fast-wiki#28]
**Describe the bug**
我们将对于框架设计上进行改动，由于第一版本的框架采用了MasaFramework+DDD+CQRS，导致项目的复杂度过高，所以新版本我们业务使用MasaFramework，但是不会使用CQRS+DDD增加项目的复杂度，我们适当的减少项目复杂，在保持更好的维护性下，也降低代码的复杂度。

后台框架技术栈：
 - MasaFramework
 - EntityFrameworkCore
 - MiniApis
 - PostgreSQL | Sqlite

**Comment by feynmanloo** [comment]
大佬为什么不考虑AbpVnext呢？

**Comment by Je88e** [comment]
目前的DDD版本希望作为分支保留
